/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = {
  regsiter: {
    label: string;
    merkle_root: string;
  };
} | {
  claim: {
    airdrop_id: number;
    beneficiary?: string | null;
    merkle_proof: string[];
  };
};
export type QueryMsg = {
  airdrop: {};
} | {
  airdrops: {};
} | {
  latest_airdrop_id: {};
} | {
  qualification: {
    beneficiary: string;
    merkle_proof: string[];
  };
};
export interface MigrateMsg {}
export interface AirdropResponse {
  id: number;
}
export type AirdropsResponse = AirdropResponse[];
export type Uint64 = number;
export interface QualificationResponse {}