/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Airdrop.types";
import * as _1 from "./Airdrop.client";
import * as _2 from "./Compat.types";
import * as _3 from "./Compat.client";
import * as _4 from "./Core.types";
import * as _5 from "./Core.client";
import * as _6 from "./Faucet.types";
import * as _7 from "./Faucet.client";
import * as _8 from "./Periphery.types";
import * as _9 from "./Periphery.client";
export namespace contracts {
  export const Airdrop = { ..._0,
    ..._1
  };
  export const Compat = { ..._2,
    ..._3
  };
  export const Core = { ..._4,
    ..._5
  };
  export const Faucet = { ..._6,
    ..._7
  };
  export const Periphery = { ..._8,
    ..._9
  };
}