/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Core.types";
import * as _1 from "./Core.client";
import * as _2 from "./Periphery.types";
import * as _3 from "./Periphery.client";
export namespace contracts {
  export const Core = { ..._0,
    ..._1
  };
  export const Periphery = { ..._2,
    ..._3
  };
}