[workspace]
members = [
    "contracts/*",
    "packages/*"
]

[profile.release.package.ibc-core]
codegen-units = 1
incremental = false

[profile.release.package.ibc-periphery]
codegen-units = 1
incremental = false

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
panic = 'abort'
incremental = false
overflow-checks = true
