[workspace]
members = ["contracts/*", "packages/*", "tests"]

[profile.release.package.ibcx-airdrop]
codegen-units = 1
incremental = false

[profile.release.package.ibcx-core]
codegen-units = 1
incremental = false

[profile.release.package.ibcx-faucet]
codegen-units = 1
incremental = false

[profile.release.package.ibcx-periphery]
codegen-units = 1
incremental = false

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
panic = 'abort'
incremental = false
overflow-checks = true
