[workspace]
members = [
    "contracts/*",
    "packages/*",
    # disable
    # "integration-test",
]


[profile.release]
codegen-units = 1
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
panic = 'abort'
incremental = false
overflow-checks = true
