[package]
name = "ibc-alias"
version = "0.1.0"
authors = ["frostornge <frostornge@gmail.com>"]
edition = "2021"

[dependencies]
cosmwasm-std = { version = "1.1.9", features = ["stargate"]}

osmo-bindings = { git = "https://github.com/osmosis-labs/bindings", rev = "531cf7b" }
