/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./Airdrop.client";
import * as _3 from "./Compat.client";
import * as _5 from "./Core.client";
import * as _7 from "./Faucet.client";
import * as _9 from "./Periphery.client";
export declare namespace contracts {
    const Airdrop: {
        AirdropQueryClient: typeof _1.AirdropQueryClient;
        AirdropClient: typeof _1.AirdropClient;
    };
    const Compat: {
        CompatQueryClient: typeof _3.CompatQueryClient;
        CompatClient: typeof _3.CompatClient;
    };
    const Core: {
        CoreQueryClient: typeof _5.CoreQueryClient;
        CoreClient: typeof _5.CoreClient;
    };
    const Faucet: {
        FaucetQueryClient: typeof _7.FaucetQueryClient;
        FaucetClient: typeof _7.FaucetClient;
    };
    const Periphery: {
        PeripheryClient: typeof _9.PeripheryClient;
    };
}
//# sourceMappingURL=index.d.ts.map