/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./Airdrop.client";
import * as _3 from "./Core.client";
import * as _5 from "./Faucet.client";
import * as _7 from "./Periphery.client";
export declare namespace contracts {
    const Airdrop: {
        AirdropQueryClient: typeof _1.AirdropQueryClient;
        AirdropClient: typeof _1.AirdropClient;
    };
    const Core: {
        CoreQueryClient: typeof _3.CoreQueryClient;
        CoreClient: typeof _3.CoreClient;
    };
    const Faucet: {
        FaucetQueryClient: typeof _5.FaucetQueryClient;
        FaucetClient: typeof _5.FaucetClient;
    };
    const Periphery: {
        PeripheryClient: typeof _7.PeripheryClient;
    };
}
//# sourceMappingURL=index.d.ts.map