name: publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching v*, i.e. v1.0, v20.15.10
      - "v[0-9]+.[0-9]+.[0-9]+-rc*" # Push events to matching v*, i.e. v1.0-rc1, v20.15.10-rc5

jobs:
  optimize-airdrop:
    name: optimize-airdrop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate Cargo.lock
        run: |
          cargo build --workspace
          cargo fetch --verbose

      - name: Build Artifacts # use beaker version of the optimizer
        run: |
          docker run --rm -v "$(pwd)":/code \
          --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
          --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
          cosmwasm/workspace-optimizer:0.12.8

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/checksums_intermediate.txt
            artifacts/checksums.txt
            artifacts/ibcx_airdrop.wasm
            artifacts/ibcx_core.wasm
            artifacts/ibcx_periphery.wasm
          body_path: CHANGELOG.md
