name: publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  optimize-airdrop:
    name: optimize-airdrop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate Cargo.lock
        run: |
          cargo build --workspace
          cargo fetch --verbose

      - name: Build Artifacts # use beaker version of the optimizer
        run: |
          docker run --rm -v "$(pwd)":/code \
          --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
          --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
          cosmwasm/workspace-optimizer:0.12.8
          tar -zcvf cosmwasm-artifacts.tar.gz artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: cosmwasm-artifacts.tar.gz
          body_path: CHANGELOG.md
